'use client'
import {useEffect,useState} from 'react';import AppNav from '../../components/AppNav';import {getSupabase} from '../../lib/supabase';import {useWorkspace} from '../../lib/useWorkspace'
const roles=['admin','partner','member','child','viewer'];
export default function Family(){const w=useWorkspace(),[members,setMembers]=useState<any[]>([]),[invites,setInvites]=useState<any[]>([]),[email,setEmail]=useState(''),[role,setRole]=useState('partner'),[name,setName]=useState(''),[msg,setMsg]=useState(''),[lastLink,setLastLink]=useState('');const admin=['owner','admin'].includes(w.role);
async function load(){if(!w.family)return;const s=await getSupabase();const {data,error}=await s.rpc('list_family_admin',{p_family_id:w.family.id});if(error){setMsg(error.message);return}setMembers(data?.members||[]);setInvites(data?.invites||[]);setName(w.family.name)}useEffect(()=>{load()},[w.family?.id]);
function link(token:string){return `${window.location.origin}/invite/${token}`}
async function copy(v:string){await navigator.clipboard.writeText(v);setMsg('Link aktivasi disalin.')}
async function invite(e:any){e.preventDefault();setMsg('');setLastLink('');const s=await getSupabase();const {data,error}=await s.rpc('invite_family_member',{p_family_id:w.family.id,p_email:email,p_role:role});if(error){setMsg(error.message);return}if(data?.status==='added'){setMsg('Email tersebut sudah punya akun. Anggota langsung ditambahkan.')}else{const u=link(data.token);setLastLink(u);setMsg('Undangan berhasil dibuat. Kirim link aktivasi ini ke anggota.')}setEmail('');load()}
async function rename(){const s=await getSupabase();const {error}=await s.from('families').update({name}).eq('id',w.family.id);setMsg(error?error.message:'Nama keluarga disimpan.')}
async function changeMember(m:any,nextRole:string){const s=await getSupabase();const {error}=await s.rpc('update_family_member',{p_family_id:w.family.id,p_user_id:m.user_id,p_role:nextRole,p_full_name:m.full_name||null});setMsg(error?error.message:'Role anggota diperbarui.');if(!error)load()}
async function remove(m:any){if(!confirm(`Hapus ${m.full_name||m.email||'anggota'} dari keluarga? Riwayat transaksi tetap disimpan.`))return;const s=await getSupabase();const {error}=await s.rpc('remove_family_member',{p_family_id:w.family.id,p_user_id:m.user_id});setMsg(error?error.message:'Anggota dihapus dari keluarga.');if(!error)load()}
async function cancel(i:any){if(!confirm(`Batalkan undangan untuk ${i.email}?`))return;const s=await getSupabase();const {error}=await s.rpc('cancel_family_invite',{p_family_id:w.family.id,p_invite_id:i.id});setMsg(error?error.message:'Undangan dibatalkan.');if(!error)load()}
async function regen(i:any){const s=await getSupabase();const {data,error}=await s.rpc('regenerate_family_invite',{p_family_id:w.family.id,p_invite_id:i.id});if(error){setMsg(error.message);return}const u=link(data.token);setLastLink(u);setMsg('Link baru dibuat dan berlaku 7 hari.');load()}
if(w.loading)return <main className="splash">Memuat…</main>;return <main className="walletPage innerPage"><header className="pageHeader"><a href="/app">‹</a><div><small>KELUARGA</small><h1>Family</h1></div><span/></header><section className="familyHero"><small>NAMA KELUARGA</small><div className="familyNameEdit"><input value={name} onChange={e=>setName(e.target.value)}/>{admin&&<button onClick={rename}>Simpan</button>}</div><p>{members.length} anggota • {w.role}</p></section><section className="panel"><div className="sectionHead"><div><small>ANGGOTA</small><h2>Keluarga kamu</h2></div></div><div className="memberList">{members.map(m=><article key={m.id}><div className="avatar">{(m.full_name||m.email||'U').slice(0,1).toUpperCase()}</div><div className="memberInfo"><strong>{m.full_name||m.email||'User Finora'}</strong><span>{m.email||''}</span></div>{m.role==='owner'?<b>Owner</b>:admin?<div className="memberActions"><select value={m.role} onChange={e=>changeMember(m,e.target.value)}>{roles.map(r=><option key={r} value={r}>{r}</option>)}</select><button type="button" className="dangerBtn" onClick={()=>remove(m)}>Hapus</button></div>:<b>{m.role}</b>}</article>)}</div></section>{admin&&<><section className="panel"><div className="sectionHead"><div><small>INVITE</small><h2>Tambah pasangan / anak</h2></div></div><form onSubmit={invite}><label className="field"><span>Email anggota</span><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="nama@email.com"/></label><label className="field"><span>Role</span><select value={role} onChange={e=>setRole(e.target.value)}>{roles.map(r=><option key={r} value={r}>{r}</option>)}</select></label><button className="primaryBtn">Buat Link Aktivasi</button></form>{lastLink&&<div className="inviteLinkBox"><small>LINK AKTIVASI • BERLAKU 7 HARI</small><input readOnly value={lastLink}/><div><button onClick={()=>copy(lastLink)}>Salin Link</button><a href={`https://wa.me/?text=${encodeURIComponent('Undangan iMersFinora: '+lastLink)}`} target="_blank" rel="noreferrer">Bagikan WhatsApp</a></div></div>}{msg&&<p className="formMsg">{msg}</p>}</section>{invites.length>0&&<section className="panel"><div className="sectionHead"><div><small>PENDING</small><h2>Undangan belum aktif</h2></div></div><div className="inviteList">{invites.map(i=>{const u=link(i.token);return <article key={i.id}><div><strong>{i.email}</strong><span>{i.role} • berlaku sampai {new Date(i.expires_at).toLocaleDateString('id-ID')}</span></div><div className="inviteActions"><button onClick={()=>copy(u)}>Salin</button><button onClick={()=>regen(i)}>Link Baru</button><button className="dangerBtn" onClick={()=>cancel(i)}>Batalkan</button></div></article>})}</div></section>}</>}<AppNav/></main>}
