'use client'
import {useEffect,useState} from 'react'
import AppNav from '../../../components/AppNav'
import {getSupabase} from '../../../lib/supabase'
import {useWorkspace} from '../../../lib/useWorkspace'

type Asset={id:string;file_name:string;public_url:string;created_at:string}
export default function Branding(){
 const w=useWorkspace(); const [assets,setAssets]=useState<Asset[]>([]); const [active,setActive]=useState(''); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false)
 async function load(){if(!w.family?.id)return;const s=await getSupabase();const [{data:a},{data:b}]=await Promise.all([s.from('brand_assets').select('id,file_name,public_url,created_at').eq('family_id',w.family.id).order('created_at',{ascending:false}),s.from('app_branding').select('pwa_icon_url').eq('family_id',w.family.id).maybeSingle()]);setAssets((a||[]) as Asset[]);setActive(b?.pwa_icon_url||'')}
 useEffect(()=>{load()},[w.family?.id])
 async function upload(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f||!w.family?.id)return;setBusy(true);setMsg('');try{if(!['image/png','image/webp'].includes(f.type))throw new Error('Gunakan PNG atau WebP.');if(f.size>2*1024*1024)throw new Error('Ukuran file maksimal 2 MB.');const buf=await f.arrayBuffer();const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',buf))).map(x=>x.toString(16).padStart(2,'0')).join('');const ext=f.type==='image/webp'?'webp':'png';const path=`${w.family.id}/${hash}.${ext}`;const s=await getSupabase();const exists=assets.find(x=>x.public_url.includes(hash));if(exists){setMsg('Gambar ini sudah ada di library. Tidak dibuat duplikat.');return}const {error:ue}=await s.storage.from('finora-branding').upload(path,f,{contentType:f.type,upsert:false});if(ue && !String(ue.message).toLowerCase().includes('already'))throw ue;const {data:u}=s.storage.from('finora-branding').getPublicUrl(path);const {error:ie}=await s.from('brand_assets').insert({family_id:w.family.id,file_name:f.name,file_hash:hash,public_url:u.publicUrl});if(ie && ie.code!=='23505')throw ie;await load();setMsg('Gambar berhasil masuk ke library. Pilih Terapkan untuk menjadikannya icon PWA.')}catch(x:any){setMsg(x?.message||'Upload gagal.')}finally{setBusy(false);e.target.value=''}}
 async function apply(url:string){if(!w.family?.id)return;setBusy(true);const s=await getSupabase();const {error}=await s.from('app_branding').upsert({family_id:w.family.id,pwa_icon_url:url,updated_at:new Date().toISOString()},{onConflict:'family_id'});setBusy(false);if(error){setMsg(error.message);return}setActive(url);setMsg('Icon aktif diperbarui. Install ulang PWA bila HP masih menampilkan icon lama.')}
 async function remove(a:Asset){if(!confirm('Hapus gambar ini dari library?'))return;const s=await getSupabase();if(active===a.public_url){setMsg('Gambar sedang dipakai sebagai icon. Terapkan gambar lain dulu.');return}const marker='/finora-branding/';const path=decodeURIComponent(a.public_url.split(marker)[1]||'');if(path)await s.storage.from('finora-branding').remove([path]);await s.from('brand_assets').delete().eq('id',a.id);await load()}
 return <main className="walletPage innerPage"><header className="pageHeader"><a href="/settings">‹</a><div><small>BRANDING</small><h1>Icon & Logo PWA</h1></div><span/></header><section className="card brandUpload"><div className="brandActive">{active?<img src={active} alt="Icon aktif"/>:<div>F</div>}<section><small>ICON AKTIF</small><strong>{active?'Custom Brand':'Default Finora'}</strong><span>Icon yang dipakai saat PWA di-install.</span></section></div><label className="uploadBox"><b>＋ Upload Icon Baru</b><span>Rekomendasi 512 × 512 px • rasio 1:1 • PNG/WebP • maks. 2 MB</span><span>Gunakan area aman ±15% agar logo tidak terpotong icon Android/iOS.</span><input type="file" accept="image/png,image/webp" onChange={upload} disabled={busy}/></label>{msg&&<p className="formMsg">{msg}</p>}</section><section className="panel"><div className="sectionHead"><div><small>MEDIA LIBRARY</small><h2>Gambar yang sudah di-upload</h2></div><span>{assets.length} gambar</span></div>{assets.length===0?<div className="brandEmpty">Belum ada gambar. Upload sekali, lalu gambar akan tersimpan di sini agar tidak upload berulang.</div>:<div className="brandGrid">{assets.map(a=><article key={a.id} className={active===a.public_url?'active':''}><img src={a.public_url} alt={a.file_name}/><div><strong>{a.file_name}</strong><span>{active===a.public_url?'Sedang digunakan':'Tersimpan di library'}</span></div><button onClick={()=>apply(a.public_url)} disabled={busy||active===a.public_url}>{active===a.public_url?'Aktif':'Terapkan'}</button><button className="brandDelete" onClick={()=>remove(a)} disabled={busy||active===a.public_url}>Hapus</button></article>)}</div>}</section><AppNav/></main>
}
