'use client'
import {useEffect,useRef,useState} from 'react'
import AppNav from '../../../components/AppNav'
import {getSupabase} from '../../../lib/supabase'
import {useWorkspace} from '../../../lib/useWorkspace'

type Asset={id:string;file_name:string;public_url:string;created_at:string}
type Pick={file:File;preview:string}
export default function Branding(){
 const w=useWorkspace(); const input=useRef<HTMLInputElement>(null)
 const [assets,setAssets]=useState<Asset[]>([]),[active,setActive]=useState(''),[pick,setPick]=useState<Pick|null>(null)
 const [msg,setMsg]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 async function load(){if(!w.family?.id)return;const s=await getSupabase();const {data,error}=await s.rpc('get_branding_library',{p_family_id:w.family.id});if(error){setError(`Media Library gagal dimuat: ${error.message}`);return}setAssets((data?.assets||[]) as Asset[]);setActive(data?.active||'');setError('')}
 useEffect(()=>{load()},[w.family?.id])
 function choose(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];setMsg('');setError('');if(!f)return;if(!['image/png','image/webp'].includes(f.type)){setError('Gunakan file PNG atau WebP.');return}if(f.size>2*1024*1024){setError('Ukuran file maksimal 2 MB.');return}if(pick?.preview)URL.revokeObjectURL(pick.preview);setPick({file:f,preview:URL.createObjectURL(f)})}
 function clearPick(){if(pick?.preview)URL.revokeObjectURL(pick.preview);setPick(null);if(input.current)input.current.value=''}
 async function upload(){if(!pick||!w.family?.id)return;setBusy(true);setMsg('');setError('');try{const f=pick.file;const buf=await f.arrayBuffer();const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',buf))).map(x=>x.toString(16).padStart(2,'0')).join('');const existing=assets.find(x=>x.public_url.includes(hash));if(existing){setMsg('Gambar yang sama sudah ada di Media Library. Tidak dibuat duplikat.');clearPick();return}const ext=f.type==='image/webp'?'webp':'png',path=`${w.family.id}/${hash}.${ext}`;const s=await getSupabase();const {error:ue}=await s.storage.from('finora-branding').upload(path,f,{contentType:f.type,upsert:false});if(ue&&!String(ue.message).toLowerCase().includes('already'))throw new Error(`Storage gagal: ${ue.message}`);const {data:u}=s.storage.from('finora-branding').getPublicUrl(path);if(!u?.publicUrl)throw new Error('Public URL gambar gagal dibuat.');const {error:re}=await s.rpc('register_brand_asset',{p_family_id:w.family.id,p_file_name:f.name,p_file_hash:hash,p_public_url:u.publicUrl});if(re)throw new Error(`Library gagal menyimpan data: ${re.message}`);await load();clearPick();setMsg('Upload berhasil. Gambar sudah tersimpan di Media Library. Klik Terapkan untuk menjadikannya icon PWA.')}catch(x:any){setError(x?.message||'Upload gagal.')}finally{setBusy(false)}}
 async function apply(url:string){if(!w.family?.id)return;setBusy(true);setMsg('');setError('');const s=await getSupabase();const {error}=await s.rpc('apply_pwa_icon',{p_family_id:w.family.id,p_public_url:url});setBusy(false);if(error){setError(`Gagal menerapkan icon: ${error.message}`);return}await load();setMsg('Icon PWA berhasil diterapkan. Untuk HP yang sudah install, uninstall lalu install ulang PWA agar icon cache ikut berubah.')}
 async function remove(a:Asset){if(!w.family?.id||!confirm('Hapus gambar ini dari Media Library?'))return;if(active===a.public_url){setError('Icon ini sedang aktif. Terapkan gambar lain terlebih dahulu.');return}setBusy(true);setMsg('');setError('');try{const s=await getSupabase();const marker='/finora-branding/',path=decodeURIComponent(a.public_url.split(marker)[1]||'');if(path){const {error:se}=await s.storage.from('finora-branding').remove([path]);if(se)throw new Error(`Storage gagal menghapus: ${se.message}`)}const {error:de}=await s.rpc('delete_brand_asset',{p_family_id:w.family.id,p_asset_id:a.id});if(de)throw de;await load();setMsg('Gambar dihapus dari Media Library.')}catch(x:any){setError(x?.message||'Gagal menghapus gambar.')}finally{setBusy(false)}}
 return <main className="walletPage innerPage"><header className="pageHeader"><a href="/settings">‹</a><div><small>BRANDING</small><h1>Icon & Logo PWA</h1></div><span/></header><section className="card brandUpload"><div className="brandActive">{active?<img src={active} alt="Icon aktif"/>:<div>F</div>}<section><small>ICON AKTIF</small><strong>{active?'Custom Brand':'Default Finora'}</strong><span>Icon yang dipakai saat PWA di-install.</span></section></div><div className="uploadBox"><b>＋ Upload Icon Baru</b><span>Rekomendasi 512 × 512 px • rasio 1:1 • PNG/WebP • maks. 2 MB</span><span>Gunakan area aman ±15% agar logo tidak terpotong icon Android/iOS.</span><input ref={input} type="file" accept="image/png,image/webp" onChange={choose} disabled={busy}/>{pick&&<div className="brandPreview"><img src={pick.preview} alt="Preview upload"/><div><strong>{pick.file.name}</strong><span>{(pick.file.size/1024).toFixed(0)} KB • {pick.file.type.replace('image/','').toUpperCase()}</span><small>Preview saja — belum di-upload.</small></div></div>}{pick&&<div className="brandConfirm"><button className="primaryBtn" onClick={upload} disabled={busy}>{busy?'Mengupload…':'Upload ke Media Library'}</button><button className="secondaryBtn" onClick={clearPick} disabled={busy}>Ganti / Batal</button></div>}</div>{msg&&<p className="formMsg successMsg">✓ {msg}</p>}{error&&<p className="formMsg errorMsg">⚠ {error}</p>}</section><section className="panel"><div className="sectionHead"><div><small>MEDIA LIBRARY</small><h2>Gambar yang sudah di-upload</h2></div><span>{assets.length} gambar</span></div>{assets.length===0?<div className="brandEmpty">Belum ada gambar yang tersimpan. Pilih file di atas lalu tekan <b>Upload ke Media Library</b>.</div>:<div className="brandGrid">{assets.map(a=><article key={a.id} className={active===a.public_url?'active':''}><img src={a.public_url} alt={a.file_name}/><div><strong>{a.file_name}</strong><span>{active===a.public_url?'Sedang digunakan':'Tersimpan di library'}</span></div><button onClick={()=>apply(a.public_url)} disabled={busy||active===a.public_url}>{active===a.public_url?'✓ Aktif':'Terapkan sebagai Icon'}</button><button className="brandDelete" onClick={()=>remove(a)} disabled={busy||active===a.public_url}>Hapus</button></article>)}</div>}</section><AppNav/></main>
}
