'use client'
import {useEffect,useState} from 'react';import AppNav from '../../../components/AppNav';import {getSupabase} from '../../../lib/supabase';import {useWorkspace} from '../../../lib/useWorkspace'
type Cat={id:string,name:string,kind:'income'|'expense'|'both',icon:string|null,color:string|null,is_active:boolean}
const labels:any={expense:'Pengeluaran',income:'Pemasukan',both:'Keduanya'}
export default function Categories(){const w=useWorkspace();const [rows,setRows]=useState<Cat[]>([]),[name,setName]=useState(''),[kind,setKind]=useState<'income'|'expense'|'both'>('expense'),[icon,setIcon]=useState('✨'),[edit,setEdit]=useState<Cat|null>(null),[msg,setMsg]=useState('');
 async function load(){if(!w.family?.id)return;const s=await getSupabase();const {data,error}=await s.from('categories').select('id,name,kind,icon,color,is_active').eq('family_id',w.family.id).order('kind').order('name');if(error)setMsg(error.message);else setRows(data||[])}
 useEffect(()=>{load()},[w.family?.id]); async function save(e:any){e.preventDefault();if(!w.family?.id)return;const s=await getSupabase();const payload={family_id:w.family.id,name:name.trim(),kind,icon:icon.trim()||'•',is_active:true};const q=edit?await s.from('categories').update(payload).eq('id',edit.id).eq('family_id',w.family.id):await s.from('categories').insert(payload);if(q.error){setMsg(q.error.message);return}setName('');setIcon('✨');setKind('expense');setEdit(null);setMsg('Kategori tersimpan.');load()}
 async function toggle(c:Cat){const s=await getSupabase();const {error}=await s.from('categories').update({is_active:!c.is_active}).eq('id',c.id);setMsg(error?error.message:'Status kategori diperbarui.');load()}
 async function del(c:Cat){if(!confirm(`Hapus kategori “${c.name}”? Transaksi lama tetap tersimpan.`))return;const s=await getSupabase();const {error}=await s.from('categories').delete().eq('id',c.id);setMsg(error?error.message:'Kategori dihapus.');load()}
 function start(c:Cat){setEdit(c);setName(c.name);setKind(c.kind);setIcon(c.icon||'✨');window.scrollTo({top:0,behavior:'smooth'})}
 if(w.loading)return <main className="splash">Memuat…</main>;return <main className="walletPage innerPage"><header className="pageHeader"><a href="/settings">‹</a><div><small>SETTINGS</small><h1>Kategori</h1></div><span/></header><section className="panel"><div className="sectionHead"><div><small>DINAMIS</small><h2>{edit?'Edit kategori':'Tambah kategori'}</h2></div></div><form onSubmit={save}><label className="field"><span>Nama kategori</span><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Contoh: Makan, Gaji, Cicilan"/></label><div className="formTwo"><label className="field"><span>Jenis</span><select value={kind} onChange={e=>setKind(e.target.value as any)}><option value="expense">Pengeluaran</option><option value="income">Pemasukan</option><option value="both">Pemasukan & Pengeluaran</option></select></label><label className="field"><span>Icon / Emoji</span><input value={icon} onChange={e=>setIcon(e.target.value)} maxLength={8}/></label></div><button className="primaryBtn">{edit?'Simpan perubahan':'Tambah kategori'}</button>{edit&&<button className="secondaryBtn" type="button" onClick={()=>{setEdit(null);setName('');setIcon('✨')}}>Batal edit</button>}</form>{msg&&<p className="formMsg">{msg}</p>}</section><section className="panel"><div className="sectionHead"><div><small>KATEGORI</small><h2>Semua kategori</h2></div><span>{rows.length} item</span></div><div className="manageList">{rows.map(c=><article key={c.id} className={!c.is_active?'disabledRow':''}><b className="catEmoji">{c.icon||'•'}</b><div><strong>{c.name}</strong><span>{labels[c.kind]} • {c.is_active?'Aktif':'Nonaktif'}</span></div><div className="rowActions"><button onClick={()=>start(c)}>Edit</button><button onClick={()=>toggle(c)}>{c.is_active?'Nonaktifkan':'Aktifkan'}</button><button className="dangerText" onClick={()=>del(c)}>Hapus</button></div></article>)}</div></section><AppNav/></main>}
